version: '3.8'
services:
  # Banco de dados (Obrigatório)
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    logging:
      driver: "none"

  # Airflow Scheduler (O "Cérebro")
  scheduler:
    image: apache/airflow:2.7.1
    depends_on:
      - postgres
    environment:
      - LOAD_EXAMPLES=False
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW__CORE__EXECUTOR=SequentialExecutor
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
    command: scheduler

  # Airflow Webserver (A Interface)
  webserver:
    image: apache/airflow:2.7.1
    depends_on:
      - postgres
    environment:
      - LOAD_EXAMPLES=False
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW__CORE__EXECUTOR=SequentialExecutor
    volumes:
      - ./Dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
    ports:
      - "8080:8080"
    command: webserver

  # Apache Solr (O Destino dos Dados)
  solr:
    image: solr:latest
    ports:
      - "8983:8983"
    container_name: solr_instance
    command: solr-precreate desafio_core